= Opinionated Dart OpenAPI v3 Plugin

This plugin was originally designed for use by the OpenAPi v3 Maven Plugin, but works with the
command line generator and the Gradle plugin. it generates _excellent_ Dart code and uses Dio.

NOTE: we are currently using 7.23.0 of the OpenAPI Maven Plugin. 

== Sponsors

This project is part of the Open Source project https://www.featurehub.io[FeatureHub], please consider sponsoring that project to support this generator if you use it.  

== FAQ

- Please note the difference between a `required` field and a `nullable` field. A required field means its contents need to be in the JSON data that is sent, regardless of its actual value (null or not), a required nullable field will be sent as null, the field will always bein the data. A nullable field just means that its field is nullable. This was a critical correction of behaviour between 7 and 8 of
this plugin.

== How to use

This tool can be used via Maven, Gradle or from the command line. There are important additional properties that
you can configure especially around support for null safety, so read on!

=== Usage in Maven

To use it, do something like this:

[source,xml]
-----
      <plugin>
        <groupId>org.openapitools</groupId>
        <artifactId>openapi-generator-maven-plugin</artifactId>
        <version>7.23.0</version>
        <dependencies>
          <dependency>
            <groupId>com.bluetrainsoftware.maven</groupId>
            <artifactId>openapi-dart-generator</artifactId>
            <version>9.1</version>
          </dependency>
        </dependencies>
        <executions>
          <execution>
            <id>mr-api</id>
            <goals>
              <goal>generate</goal>
            </goals>
            <phase>generate-sources</phase>
            <configuration>
              <output>${project.basedir}</output>
              <inputSpec>${project.basedir}/target/mrapi/mr-api.yaml</inputSpec>
              <generatorName>dart2-api</generatorName>
              <enablePostProcessFile>true</enablePostProcessFile>
              <additionalProperties>
                <additionalProperty>
                  pubName=k8s_api
                </additionalProperty>
                <additionalProperty>
                  useDio5=true
                </additionalProperty>
              </additionalProperties>
            </configuration>
          </execution>
        </executions>
      </plugin>
-----

We use the enablePostProcessFile because if it finds a FLUTTER environment variable, it
will run dartfmt on the generated files.

=== Usage in Gradle

In Gradle, you have to make this extra library available to the buildscript, so at the top of your file before
your plugin declaration you need a section similar to:

[source,groovy]
----
buildscript {
	repositories {
		mavenLocal()
		mavenCentral()
	}
	dependencies {
		classpath "com.bluetrainsoftware.maven:openapi-dart-generator:9.1"
	}
}
----

from there in your openApiGenerator definitions, you specify the server format in additional properties:

[source,groovy]
----
openApiGenerate {
    generatorName = "dart2-api"
    inputSpec = openApiSpec
    outputDir = openApiOutputDir
    apiPackage = "com.your-company.api"
    modelPackage = "com.your-company.api.model"
	  additionalProperties = [
	    'key': 'value'
	  ]
    configOptions = [:]
}
----

=== Usage from the command line

Please refer to the article https://medium.com/@irinasouthwell_220/accelerate-flutter-development-with-openapi-and-dart-code-generation-1f16f8329a6a[on Medium].

Please note the versions of all the libraries have moved on since then. DO NOT continue using OpenAPi 5.1.

==== Additional Properties

Additional properties allow you to customise how code is generated and we honour 2 of them above the normal ones.

- `useDio5`: this will make  the library use Dio5 and the associated OpenAPI common
library associated with Dio5.
- `pubspec-dependencies`: anything in this will be split on a command added to the dependencies section of your
generated code.
- `pubspec-dev-dependencies`: anything here will be added to the dev dependencies of your generated code.
- `listAnyOf=false` - this will turn _off_ AnyOf support. This would be a bit weird, but you can do it if you want.
- `disableCopyWith` - if this is specified, then the copyWith functionality will be disabled. On complex OpenAPI definitions, the combinations of null safety and nested classes can cause incomplete or invalid code to be generated. We recommend disabling the generation of the copy-with code for that purpose. It is simply a convenience for coding and is not required as part of the API.

the normal ones include:

----
name: {{pubName}}
version: {{pubVersion}}
description: {{pubDescription}}
----

They are specified in the configuration above (Maven example here):

[source,xml]
----
<configuration>
  <output>${project.basedir}</output>
  <inputSpec>${project.basedir}/target/mrapi/mr-api.yaml</inputSpec>
  <generatorName>dart2-api</generatorName>
  <enablePostProcessFile>true</enablePostProcessFile>
    <additionalProperties>
      <additionalProperty>pubName=myapi</additionalProperty>
    </additionalProperties>
</configuration>
----

See the `src/it` project for more examples.

==== Additional files

You may need to use additional files - just add them to the project or add them via a dependency. You can use the
`importMappings` section of the configuration to bring in any packages (internal or external) into the library
definition. For example

[source,xml]
----
<typeMappings>int-or-string=IntOrString</typeMappings>
<importMappings>IntOrString=./int_or_string.dart</importMappings>
----

This will note anything that has `format: int-or-string` and map this to the class IntOrString and there will be an
extra `part` import for it added to the library main. You must write this class to have the expected criteria from
the rest of the library but it does allow you to support custom types. Again, an example of this is in `src/it`.

If you use something like this instead:

[source,xml]
----
<typeMappings>int-or-string=IntOrString</typeMappings>
<importMappings>IntOrString=package:k8s-dart/int_or_string.dart</importMappings>
----

Then it will add it to the `import` section of your library allowing
you to use external libraries.

==== Using dependencies to pull in apis from other artifacts

We typically use the Dependency Plugin to copy the actual OpenAPI yaml file from a different
project - such as in this case "mr-api".

NOTE: you can also customise this using my https://github.com/ClearPointNZ/connect-java/tree/master/maven-plugins/merge-yaml-plugin[MergeYaml plugin] if you wish to merge apis together. If often do this
for testing purposes.

[source,xml]
----
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-dependency-plugin</artifactId>
        <executions>
          <execution>
            <id>unpack todo api</id>
            <phase>initialize</phase>
            <goals>
              <goal>unpack</goal>
            </goals>
            <configuration>
              <artifactItems>
                <artifactItem>
                  <groupId>io.yourapi.mr</groupId>
                  <artifactId>mr-api</artifactId>
                  <version>1.1-SNAPSHOT</version>
                  <type>jar</type>
                  <outputDirectory>${project.basedir}/target/mrapi/</outputDirectory>
                </artifactItem>
              </artifactItems>
              <includes>
                **/*.yaml
              </includes>
              <overWriteReleases>true</overWriteReleases>
              <overWriteSnapshots>true</overWriteSnapshots>
            </configuration>
          </execution>
        </executions>
      </plugin>
----

And we include a custom Clean plugin definition to ensure old artifacts aren't left
behind as you generate.

[source,xml]
----
      <plugin>
        <artifactId>maven-clean-plugin</artifactId>
        <version>3.1.0</version>
        <configuration>
          <filesets>
            <fileset>
              <directory>lib</directory>
              <includes>
                <include>**/**</include>
              </includes>
            </fileset>
            <fileset>
              <directory>docs</directory>
              <includes>
                <include>**/**</include>
              </includes>
            </fileset>
            <fileset>
              <directory>test</directory>
              <includes>
                <include>**/**</include>
              </includes>
            </fileset>
            <fileset>
              <directory>.openapi-generator</directory>
              <includes>
                <include>**/**</include>
              </includes>
            </fileset>
            <fileset>
              <directory>.openapi-generator</directory>
              <includes>
                <include>**/**</include>
              </includes>
            </fileset>
          </filesets>
        </configuration>
      </plugin>
----

=== I need to do something special with the Dio layer!

The DioClientDelegate we provide can be fully overridden - in Dart all classes are also interfaces so if you wish
to do special things in the underlying "guts" of the Dio library you can easily do so. Caching is an example, one
of our users has an https://gist.github.com/Maczuga/255e822a09f8d3dd8284096e5cda3003[example]:

Ensure you include 304 as a valid return type for cached APIs.

[source,dart]
----
import 'package:dio_cache_interceptor/dio_cache_interceptor.dart';
import 'package:openapi_dart_common/openapi.dart';
import 'package:xxxx/api_delegate.dart'; // The file below

final _cacheOptions = CacheOptions(
  store: MemCacheStore(),
  hitCacheOnErrorExcept: [401, 403],
  maxStale: const Duration(days: 7),
);

class API extends ApiClient {
    API._internal() : super(basePath: "https://xxxxxx/api") {
    apiClientDelegate = CustomDioClientDelegate();
    final dioDelegate = apiClientDelegate as CustomDioClientDelegate;
    dioDelegate.client.interceptors.add(DioCacheInterceptor(options: _cacheOptions));
  }
}
----

[source,dart]
----
import 'dart:convert';

import 'package:dio/dio.dart';
import 'package:openapi_dart_common/openapi.dart';

class CustomDioClientDelegate implements DioClientDelegate {
  @override
  final Dio client;

  CustomDioClientDelegate([Dio? client]) : client = client ?? Dio();

  @override
  Future<ApiResponse> invokeAPI(
      String basePath, String path, Iterable<QueryParam> queryParams, Object? body, Options options,
      {bool passErrorsAsApiResponses = false}) async {
    final String url = basePath + path;

    // fill in query parameters
    final Map<String, String> qParams = _convertQueryParams(queryParams);

    options.responseType = ResponseType.plain;
    options.receiveDataWhenStatusError = true;

    // Dio can't cope with this in both places, it just adds them together in a stupid way
    if (options.headers != null && options.headers!['Content-Type'] != null) {
      options.contentType = options.headers!['Content-Type']?.toString();
      options.headers!.remove('Content-Type');
    }

    try {
      Response<String> response;

      if (['GET', 'HEAD', 'DELETE'].contains(options.method)) {
        response = await client.request<String>(url, options: options, queryParameters: qParams);
      } else {
        response = await client.request<String>(url, options: options, data: body, queryParameters: qParams);
      }

      final stream = _jsonToStream(response.data);
      return ApiResponse(response.statusCode ?? 500, _convertHeaders(response.headers), stream);
    } catch (ex, stack) {
      if (ex is! DioError) rethrow;

      if (passErrorsAsApiResponses) {
        if (ex.response == null) {
          return ApiResponse(500, {}, null)
            ..innerException = ex
            ..stackTrace = stack;
        }

        // if (e.response.data)
        if (ex.response!.data is String?) {
          final response = ex.response!;
          final json = response.data as String;

          return ApiResponse(response.statusCode ?? 500, _convertHeaders(response.headers), _jsonToStream(json));
        } else {
          print(
              "ex is not 'String?' ${ex.response.runtimeType.toString()} ${ex.response!.data?.runtimeType.toString() ?? ''}");
        }
      }

      if (ex.response == null) {
        throw ApiException.withInner(500, 'Connection error', ex, stack);
      } else {
        throw ApiException.withInner(ex.response?.statusCode ?? 500, ex.response?.data as String?, ex, stack);
      }
    }
  }

  Map<String, String> _convertQueryParams(Iterable<QueryParam> queryParams) {
    final Map<String, String> qp = {};
    for (final q in queryParams) {
      qp[q.name] = q.value;
    }
    return qp;
  }

  Map<String, List<String>> _convertHeaders(Headers headers) {
    final Map<String, List<String>> res = {};
    headers.forEach((k, v) => res[k] = v);
    return res;
  }

  Stream<List<int>> _jsonToStream(String? json) {
    return Stream<List<int>>.value(utf8.encode(json ?? ""));
  }
}
----
=== Testing

If you are trying to make changes to the repository, I recommend adding a new test to "SampleRunner"
with your options - you can change it to point to your own yaml OpenAPI file and it will generate the project
into `target/SampleRunner`. Also open this project (from `target/SampleRunner`) in the IDE and you will be able to
run the test and regenerate the project (just don't do a mvn clean).

If you run and debug the test in the IDE it means you can see what OpenAPI is putting in what places and see
the breakdown of the structures and tagging that is going on.

If you add something, please make sure you provide integration tests - so add the parts of the yaml that don't
otherwise work to the projects in src/it/* projects and run the `mvn verify` command. Please make sure you add tests
to the test subfolder to ensure the code is generating and working the way you want, especially if you add stuff
to the deep copy mechanism, the hash or equals mechanisms.

To test locally you can run tests by invoking this command:

[source,bash]
----
mvn clean verify
----

The source for the tests is located in src/k8s** folders. The generated test output will be in target/it/k8s**.

==== Changelog


[source,xml]
----
  <globalProperties>
    <skipFormModels>false</skipFormModels>
  </globalProperties>
----

